export const API_TAG_METADATA = 'swagger/api-tag'
export const API_HEADER_METADATA = 'swagger/api-header'
export const API_OPERATION_METADATA = 'swagger/api-operation'
export const API_EXTRA_MODELS_METADATA = 'swagger/api-extra-models'
export const API_CONSUMES_METADATA = 'swagger/api-consumes'
export const API_EXTENSION_METADATA = 'swagger/api-extension'
export const API_EXCLUDE_ENDPOINT_METADATA = 'swagger/api-exclude-endpoint'
export const API_EXCLUDE_CONTROLLER_METADATA = 'swagger/api-exclude-controller'
export const API_SECURITY_METADATA = 'swagger/api-security'
export const API_PARAMETERS_METADATA = 'swagger/api-parameters'
export const API_PRODUCES_METADATA = 'swagger/api-produces'
export const API_MODEL_PROPERTIES_METADATA = 'swagger/api-model-properties'
export const API_MODEL_PROPERTIES_ARRAY_METADATA = 'swagger/api-model-properties-array'
export const API_RESPONSE_METADATA = 'swagger/api-response'

export const METADATA_FACTORY_NAME = '_OPENAPI_METADATA_FACTORY'